# Generated by Django 6.0.2 on 2026-05-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'indexes': [models.Index(fields=['nome'], name='organizacao_nome_bef416_idx')],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('ESCOLA', 'Escola'), ('UPA', 'UPA'), ('HOSPITAL', 'Hospital'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicoes', to='organizacao.secretaria')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'indexes': [models.Index(fields=['nome', 'secretaria'], name='organizacao_nome_4e45fe_idx'), models.Index(fields=['tipo'], name='organizacao_tipo_5b26ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('nome', 'secretaria'), name='unique_instituicao_por_secretaria')],
            },
        ),
    ]
