# Generated by Django 6.0.2 on 2026-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ESCOLA', 'Escola'), ('CRECHE', 'Creche'), ('UPA', 'UPA'), ('HOSPITAL', 'Hospital'), ('OUTRO', 'Outro')], max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
