# Generated by Django 6.0.2 on 2026-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_alter_instituicao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterUniqueTogether(
            name='instituicao',
            unique_together={('nome', 'secretaria')},
        ),
    ]
