# Generated by Django 6.0.2 on 2026-04-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='PessoaTipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False, verbose_name='É o serviço principal?')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_vinculados', to='pessoas_v1.pessoa')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_vinculadas', to='pessoas_v1.tiposervico')),
            ],
            options={
                'verbose_name': 'Vínculo Pessoa-Serviço',
                'verbose_name_plural': 'Vínculos Pessoa-Serviço',
                'unique_together': {('pessoa', 'tipo_servico')},
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipos_servico',
            field=models.ManyToManyField(related_name='pessoas', through='pessoas_v1.PessoaTipoServico', to='pessoas_v1.tiposervico'),
        ),
    ]
