# Generated by Django 6.0.2 on 2026-04-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='tipos_servico',
        ),
        migrations.DeleteModel(
            name='PessoaTipoServico',
        ),
        migrations.DeleteModel(
            name='TipoServico',
        ),
    ]
