# Generated by Django 6.0.2 on 2026-05-04 07:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Combustível',
                'verbose_name_plural': 'Tipos de Combustível',
                'indexes': [models.Index(fields=['nome'], name='frota_tipoc_nome_82bc1c_idx'), models.Index(fields=['ativo'], name='frota_tipoc_ativo_b6a5b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('detalhes', models.CharField(blank=True, max_length=256, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_sugeridas', to='organizacao.secretaria')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotass',
                'indexes': [models.Index(fields=['nome'], name='frota_rota_nome_45ae07_idx'), models.Index(fields=['secretaria'], name='frota_rota_secreta_9b3c12_idx'), models.Index(fields=['ativa'], name='frota_rota_ativa_c272c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'secretaria'), name='unique_slug_por_secretaria')],
                'unique_together': {('nome', 'secretaria')},
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=9, unique=True)),
                ('categoria', models.CharField(choices=[('CARRO', 'Carro'), ('CAMINHONETE', 'Caminhonete'), ('ONIBUS', 'Ônibus'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('MAQUINA_PESADA', 'Máquina Pesada/Trator')], max_length=50)),
                ('hodometro_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Hodômetro Atual')),
                ('unidade_consumo', models.CharField(choices=[('KM_POR_L', 'km/L'), ('L_POR_H', 'L/h')], default='KM_POR_L', max_length=20)),
                ('consumo_estimado_combustivel', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('consumo_estimado_oleo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('capacidade_carga_kg', models.FloatField(blank=True, null=True)),
                ('capacidade_pessoas', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.tipocombustivel')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'indexes': [models.Index(fields=['placa'], name='frota_veicu_placa_92dce2_idx'), models.Index(fields=['modelo'], name='frota_veicu_modelo_53eb05_idx'), models.Index(fields=['ativo'], name='frota_veicu_ativo_ae4ab1_idx'), models.Index(fields=['categoria'], name='frota_veicu_categor_5ec55b_idx')],
            },
        ),
    ]
