# Generated by Django 6.0.2 on 2026-04-29 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Combustível',
                'verbose_name_plural': 'Tipos de Combustível',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=9, unique=True)),
                ('categoria', models.CharField(choices=[('CARRO', 'Carro'), ('CAMINHONETE', 'Caminhonete'), ('ONIBUS', 'Ônibus'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('MAQUINA_PESADA', 'Máquina Pesada/Trator')], max_length=50)),
                ('hodometro_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Hodômetro Atual')),
                ('unidade_consumo', models.CharField(choices=[('KM_POR_L', 'km/L'), ('L_POR_H', 'L/h')], default='KM_POR_L', max_length=20)),
                ('consumo_estimado_combustivel', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('capacidade_carga_kg', models.FloatField(blank=True, null=True)),
                ('capacidade_pessoas', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Veículo (Frota)',
                'verbose_name_plural': 'Veículos (Frota)',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('detalhes', models.CharField(blank=True, max_length=256, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_sugeridas', to='organizacao.secretaria')),
            ],
            options={
                'verbose_name': 'Rota Sugerida',
                'verbose_name_plural': 'Rotas Sugeridas',
                'unique_together': {('nome', 'secretaria')},
            },
        ),
    ]
