# Generated by Django 6.0.2 on 2026-04-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('consumo_estimado_combustivel', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Consumo Estimado (Combustível)')),
                ('consumo_estimado_oleo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Consumo Estimado (Óleo)')),
                ('detalhes', models.CharField(max_length=256)),
                ('tipo_locomocao', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial')], max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='organizacao.instituicao')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='organizacao.secretaria')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('tipo_locomocao', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial')], max_length=50)),
                ('capacidade_carga_kg', models.FloatField()),
                ('capacidade_pessoas', models.IntegerField()),
                ('consumo_estimado_combustivel', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Consumo Estimado (Combustível)')),
                ('consumo_estimado_oleo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Consumo Estimado (Óleo)')),
                ('hodometro_atual', models.FloatField()),
                ('unidade_consumo', models.CharField(choices=[('KM_POR_L', 'km/L'), ('L_POR_H', 'L/h')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='organizacao.secretaria')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.tipocombustivel')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
