# Generated by Django 6.0.7 on 2026-08-31 20:30

from django.db import migrations, models


def unificar_barco_em_catraia(apps, schema_editor):
    """Unificação do enum de embarcação: BARCO -> CATRAIA."""
    Veiculo = apps.get_model('frota', 'Veiculo')
    Veiculo.objects.filter(categoria='BARCO').update(categoria='CATRAIA')


def reverter_catraia_para_barco(apps, schema_editor):
    """Reversão best-effort (apenas o que era BARCO)."""
    Veiculo = apps.get_model('frota', 'Veiculo')
    Veiculo.objects.filter(categoria='CATRAIA', modelo__icontains='bar').update(categoria='BARCO')


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('CARRO', 'Carro'), ('CAMINHONETE', 'Caminhonete'), ('ONIBUS', 'Ônibus'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('CATRAIA', 'Catraia (Embarcação)'), ('MAQUINA_PESADA', 'Máquina Pesada/Trator')], max_length=50),
        ),
        # Unificação do enum de embarcação: BARCO -> CATRAIA (dados)
        migrations.RunPython(
            unificar_barco_em_catraia,
            reverter_catraia_para_barco,
        ),
    ]
