# Generated by Django 6.0.2 on 2026-05-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocombustivel',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
