# Generated by Django 6.0.2 on 2026-04-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.tipocombustivel'),
        ),
    ]
