# Generated by Django 6.0.2 on 2026-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='detalhes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='tipo_locomocao',
            field=models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial')], default='TERRESTRE', max_length=50),
        ),
    ]
