# Generated by Django 6.0.2 on 2026-04-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_alter_rota_detalhes_alter_rota_tipo_locomocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='consumo_estimado_combustivel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Consumo Estimado (Combustível)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_carga_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacidade de Carga (kg)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_pessoas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidade de Pessoas'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='consumo_estimado_combustivel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Consumo Estimado (Combustível)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='hodometro_atual',
            field=models.FloatField(verbose_name='Hodômetro Inicial'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_locomocao',
            field=models.CharField(blank=True, choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='unidade_consumo',
            field=models.CharField(choices=[('KM_POR_L', 'km/L'), ('L_POR_H', 'L/h')], default='KM_POR_L', max_length=20),
        ),
    ]
