# Generated by Django 6.0.2 on 2026-04-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_alter_rota_consumo_estimado_combustivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.tipoveiculo'),
        ),
    ]
