# Generated by Django 6.0.2 on 2026-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_alter_veiculo_tipo_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=200),
        ),
    ]
