# Generated by Django 6.0.2 on 2026-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='consumo_estimado_combustivel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='consumo_estimado_oleo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_carga_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_pessoas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='consumo_estimado_combustivel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='consumo_estimado_oleo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='veiculo',
            unique_together={('modelo', 'placa')},
        ),
    ]
