# Generated by Django 6.0.2 on 2026-04-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0006_alter_rota_consumo_estimado_combustivel_and_more'),
        ('organizacao', '0003_alter_secretaria_sigla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together={('nome', 'instituicao')},
        ),
    ]
