# Generated by Django 6.0.2 on 2026-04-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_alter_rota_nome_alter_rota_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='hodometro_atual',
            field=models.FloatField(default=0, verbose_name='Hodômetro Inicial'),
        ),
    ]
