# Generated by Django 6.0.2 on 2026-04-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('consumo_estimado_combustivel', models.IntegerField(default=0)),
                ('consumo_estimado_oleo', models.IntegerField(default=0)),
                ('tipo_locomocao', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial')], max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='organizacao_v1.instituicao')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='organizacao_v1.secretaria')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('tipo_locomocao', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial')], max_length=50)),
                ('capacidade_carga_kg', models.FloatField()),
                ('capacidade_pessoas', models.IntegerField()),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL_S10', 'Diesel S10'), ('DIESEL', 'Diesel Comum'), ('ETANOL', 'Etanol'), ('GNV', 'GNV')], max_length=50)),
                ('consumo_estimado_combustivel', models.IntegerField()),
                ('consumo_estimado_oleo', models.IntegerField()),
                ('hodometro_atual', models.FloatField()),
                ('unidade_consumo', models.CharField(choices=[('KM_POR_L', 'km/L'), ('L_POR_H', 'L/h')], max_length=20)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='organizacao_v1.secretaria')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
