# Generated by Django 6.0.2 on 2026-04-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ESCOLA', 'Escola'), ('CRECHE', 'Creche'), ('UPA', 'UPA'), ('HOSPITAL', 'Hospital'), ('OUTRO', 'Outro')], max_length=100)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituicoes', to='organizacao_v1.secretaria')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
    ]
