# Generated by Django 6.0.2 on 2026-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='tipo',
            field=models.CharField(choices=[('ESCOLA', 'Escola'), ('CRECHE', 'Creche'), ('UPA', 'UPA'), ('HOSPITAL', 'Hospital'), ('OUTRO', 'Outro')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=10, verbose_name='Sigla'),
        ),
    ]
