# Generated by Django 6.0.2 on 2026-04-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota_v1', '0002_alter_veiculo_placa'),
        ('organizacao_v1', '0002_alter_instituicao_nome_alter_instituicao_tipo_and_more'),
        ('pessoas_v1', '0002_remove_pessoa_tipos_servico_delete_pessoatiposervico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('quantidade_combustivel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtd Combustível (L)')),
                ('quantidade_oleo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtd Óleo (L)')),
                ('hodometro_atual', models.PositiveIntegerField(verbose_name='Hodômetro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='pessoas_v1.pessoa', verbose_name='Pessoa')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota_v1.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='organizacao_v1.secretaria', verbose_name='Secretaria')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota_v1.veiculo', verbose_name='Veículo')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='operacao_v1.tiposervico')),
            ],
            options={
                'verbose_name': 'Guia de Abastecimento',
                'verbose_name_plural': 'Guias de Abastecimento',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='OperadorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False, verbose_name='É o operador principal?')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_operados', to='pessoas_v1.pessoa', verbose_name='Pessoa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='frota_v1.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Operador de Veículo',
                'verbose_name_plural': 'Operadores de Veículos',
                'unique_together': {('pessoa', 'veiculo')},
            },
        ),
        migrations.CreateModel(
            name='AlocacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False, verbose_name='É o serviço principal?')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_alocados', to='pessoas_v1.pessoa', verbose_name='Pessoa')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='operacao_v1.tiposervico', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Alocação de Serviço',
                'verbose_name_plural': 'Alocações de Serviço',
                'unique_together': {('pessoa', 'tipo_servico')},
            },
        ),
    ]
