# Generated by Django 6.0.2 on 2026-04-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('organizacao', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False, verbose_name='É o operador principal?')),
            ],
            options={
                'verbose_name': 'Operador de Veículo',
                'verbose_name_plural': 'Operadores de Veículos',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False, verbose_name='É o serviço principal?')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_alocados', to='pessoas.pessoa', verbose_name='Pessoa')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='organizacao.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Alocação de Serviço',
                'verbose_name_plural': 'Alocações de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('rota_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_servico_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade_combustivel', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qtd Combustível (L)')),
                ('quantidade_oleo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtd Óleo (L)')),
                ('periodo_uso_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período de Uso (dias)')),
                ('hodometro_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hodômetro Atual')),
                ('hodometro_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hodômetro Anterior')),
                ('distancia_percorrida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distância Percorrida')),
                ('observacao', models.TextField(blank=True, max_length=256, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='organizacao.instituicao', verbose_name='Instituição')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='pessoas.pessoa', verbose_name='Motorista')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='organizacao.secretaria', verbose_name='Secretaria')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.tipocombustivel')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Guia de Abastecimento',
                'verbose_name_plural': 'Guias de Abastecimento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
