# Generated by Django 6.0.2 on 2026-04-29 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('organizacao', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Operador de Veículo',
                'verbose_name_plural': 'Operadores de Veículos',
            },
        ),
        migrations.CreateModel(
            name='RegistroHodometroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('hodometro_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hodometro_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia_percorrida', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Atividade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividade',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_alocados', to='pessoas.pessoa')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='organizacao.secretaria')),
            ],
            options={
                'verbose_name': 'Alocação de Atividade',
                'verbose_name_plural': 'Alocações de Atividades',
            },
        ),
        migrations.CreateModel(
            name='GuiaAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('modalidade', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('FLUVIAL', 'Fluvial'), ('ROCAGEM', 'Roçagem'), ('BORRIFACAO', 'Borrifação'), ('COROTE', 'Corote')], max_length=20)),
                ('rota_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacao_avulsa', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_litros', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_oleo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('periodo_uso_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=256, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacao.instituicao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoa')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frota.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacao.secretaria')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.tipocombustivel')),
            ],
            options={
                'verbose_name': 'Guia de Abastecimento',
                'verbose_name_plural': 'Guias de Abastecimento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
