# Generated by Django 6.0.2 on 2026-05-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('operacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaabastecimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiaabastecimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.veiculo'),
        ),
        migrations.AddField(
            model_name='registrohodometrodiario',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='operacao.guiaabastecimento'),
        ),
        migrations.AddField(
            model_name='guiaabastecimento',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacao.tipoatividade'),
        ),
        migrations.AddConstraint(
            model_name='guiaabastecimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_veiculo__isnull', True), ('veiculo__isnull', False), ('veiculo_descricao__isnull', True)), models.Q(('tipo_veiculo__isnull', False), ('veiculo__isnull', True), ('veiculo_descricao__isnull', False)), _connector='OR'), name='guia_veiculo_fk_ou_dupla_avulsa'),
        ),
    ]
