# Generated by Django 6.0.2 on 2026-04-11 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('operacao', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AddField(
            model_name='guia',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='operadorveiculo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_operados', to='pessoas.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='operadorveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='frota.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='guia',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='operacao.tiposervico'),
        ),
        migrations.AddField(
            model_name='alocacaoservico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='operacao.tiposervico', verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterUniqueTogether(
            name='operadorveiculo',
            unique_together={('pessoa', 'veiculo')},
        ),
        migrations.AlterUniqueTogether(
            name='alocacaoservico',
            unique_together={('pessoa', 'tipo_servico')},
        ),
    ]
