# Generated by Django 6.0.2 on 2026-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='observacao',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
