# Generated by Django 6.0.2 on 2026-04-29 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('operacao', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaabastecimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiaabastecimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frota.veiculo'),
        ),
        migrations.AddField(
            model_name='operadorveiculo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_operados', to='pessoas.pessoa'),
        ),
        migrations.AddField(
            model_name='operadorveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='frota.veiculo'),
        ),
        migrations.AddField(
            model_name='registrohodometrodiario',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='operacao.guiaabastecimento'),
        ),
        migrations.AddField(
            model_name='guiaabastecimento',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacao.tipoatividade'),
        ),
        migrations.AddField(
            model_name='alocacaoservico',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='operacao.tipoatividade'),
        ),
        migrations.AlterUniqueTogether(
            name='operadorveiculo',
            unique_together={('pessoa', 'veiculo')},
        ),
        migrations.AlterUniqueTogether(
            name='alocacaoservico',
            unique_together={('pessoa', 'tipo_atividade')},
        ),
    ]
