# Generated by Django 6.0.2 on 2026-04-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_guia_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='rota_texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='tipo_servico_texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='observacao',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
