# Generated by Django 6.0.2 on 2026-04-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='periodo_uso_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Período de Uso (dias)'),
        ),
    ]
