# Generated by Django 6.0.2 on 2026-05-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaabastecimento',
            name='hodometro',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hodômetro'),
        ),
    ]
