# Generated by Django 6.0.2 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
