# Generated by Django 6.0.2 on 2026-04-17 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0006_alter_rota_consumo_estimado_combustivel_and_more'),
        ('operacao', '0002_initial'),
        ('organizacao', '0003_alter_secretaria_sigla_and_more'),
        ('pessoas', '0003_alter_pessoa_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaoservico',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alocacaoservico',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_alocados', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='alocacaoservico',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='organizacao.secretaria'),
        ),
        migrations.AlterField(
            model_name='alocacaoservico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_alocadas', to='operacao.tiposervico'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='distancia_percorrida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guia',
            name='hodometro_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guia',
            name='hodometro_atual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guia',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='organizacao.instituicao'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='periodo_uso_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='quantidade_combustivel',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guia',
            name='quantidade_oleo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='organizacao.secretaria'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guia',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.veiculo'),
        ),
        migrations.AlterField(
            model_name='operadorveiculo',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operadorveiculo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_operados', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='operadorveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='frota.veiculo'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço'),
        ),
    ]
