# Generated by Django 6.0.2 on 2026-04-30 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
        ('operacao', '0002_initial'),
        ('organizacao', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='guiaabastecimento',
            old_name='quantidade_litros',
            new_name='quantidade_combustivel',
        ),
        migrations.RenameField(
            model_name='guiaabastecimento',
            old_name='identificacao_avulsa',
            new_name='veiculo_descricao',
        ),
        migrations.AddField(
            model_name='guiaabastecimento',
            name='tipo_veiculo',
            field=models.CharField(blank=True, choices=[('CARRO', 'Carro'), ('CAMINHONETE', 'Caminhonete'), ('ONIBUS', 'Ônibus'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('BARCO', 'Barco'), ('MAQUINA_PESADA', 'Máquina Pesada/Trator')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='guiaabastecimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_veiculo__isnull', True), ('veiculo__isnull', False), ('veiculo_descricao__isnull', True)), models.Q(('tipo_veiculo__isnull', False), ('veiculo__isnull', True), ('veiculo_descricao__isnull', True)), models.Q(('tipo_veiculo__isnull', True), ('veiculo__isnull', True), ('veiculo_descricao__isnull', False)), _connector='OR'), name='guia_um_tipo_veiculo'),
        ),
    ]
