# Generated by Django 6.0.7 on 2026-08-31 20:30

from django.db import migrations, models


def unificar_barco_em_catraia(apps, schema_editor):
    """Unificação do enum de embarcação: BARCO -> CATRAIA."""
    Guia = apps.get_model('operacao', 'GuiaAbastecimento')
    Guia.objects.filter(tipo_veiculo='BARCO').update(tipo_veiculo='CATRAIA')


def reverter_catraia_para_barco(apps, schema_editor):
    """Reversão best-effort (apenas o que era BARCO)."""
    Guia = apps.get_model('operacao', 'GuiaAbastecimento')
    Guia.objects.filter(tipo_veiculo='CATRAIA', veiculo_descricao__icontains='bar').update(tipo_veiculo='BARCO')


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='tipo_veiculo',
            field=models.CharField(blank=True, choices=[('CARRO', 'Carro'), ('CAMINHONETE', 'Caminhonete'), ('ONIBUS', 'Ônibus'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('CATRAIA', 'Catraia (Embarcação)'), ('MAQUINA_PESADA', 'Máquina Pesada/Trator')], max_length=50, null=True),
        ),
        # Unificação do enum de embarcação: BARCO -> CATRAIA (dados)
        migrations.RunPython(
            unificar_barco_em_catraia,
            reverter_catraia_para_barco,
        ),
    ]
