# Generated by Django 6.0.2 on 2026-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0003_guiaabastecimento_hodometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaabastecimento',
            name='hodometro_quebrado',
            field=models.BooleanField(default=False, verbose_name='Hodômetro Quebrado'),
        ),
    ]
