# Generated by Django 6.0.2 on 2026-05-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0004_guiaabastecimento_hodometro_quebrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='modalidade',
            field=models.CharField(choices=[('ONIBUS', 'Ônibus'), ('CAMINHONETE', 'Caminhonete'), ('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CATRAIA', 'Catraia'), ('COROTE', 'Corote'), ('CARRO_PASSEIO', 'Carro Passeio')], max_length=20),
        ),
    ]
