# Generated by Django 6.0.2 on 2026-05-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['-ativo', 'nome'],
                'indexes': [models.Index(fields=['nome'], name='pessoas_pes_nome_549cf3_idx'), models.Index(fields=['cpf'], name='pessoas_pes_cpf_b64cbb_idx'), models.Index(fields=['ativo'], name='pessoas_pes_ativo_a717a9_idx')],
            },
        ),
    ]
